"use client";
import { useState } from "react";
import { Download, ChevronDown } from "lucide-react";
import { LaunchPlaybook, ExtractedInsights } from "@/lib/types";
import { cn } from "@/lib/utils";

interface DownloadButtonProps {
  playbook: LaunchPlaybook;
  insights: ExtractedInsights;
}

function buildMarkdown(playbook: LaunchPlaybook, insights: ExtractedInsights): string {
  const lines: string[] = [
    `# Launch Playbook: ${insights.featureName}`,
    ``,
    `> ${insights.summary}`,
    ``,
    `**Launch Readiness Score:** ${playbook.launchReadinessScore}/100`,
    ``,
    `---`,
    ``,
    `## Recommended Launch Style: ${playbook.recommendedStyle.name}`,
    ``,
    playbook.recommendedStyle.description,
    ``,
    `**Core message:** ${playbook.recommendedStyle.messagingAngle}`,
    ``,
    `**Pros:**`,
    ...playbook.recommendedStyle.pros.map((p) => `- ${p}`),
    ``,
    `**Cons:**`,
    ...playbook.recommendedStyle.cons.map((c) => `- ${c}`),
    ``,
    `---`,
    ``,
    `## Messaging`,
    ``,
    `**Headline:** ${playbook.messaging.headline}`,
    ``,
    `**Subheadline:** ${playbook.messaging.subheadline}`,
    ``,
    `**CTA:** ${playbook.messaging.cta}`,
    ``,
    `**Key Messages:**`,
    ...playbook.messaging.keyMessages.map((m) => `- ${m}`),
    ``,
    `---`,
    ``,
    `## Rollout Phases`,
    ``,
    ...playbook.phases.flatMap((ph) => [
      `### ${ph.phase} (${ph.duration})`,
      ``,
      ...ph.actions.map((a) => `- ${a}`),
      ``,
      `✓ **Success metric:** ${ph.successMetric}`,
      ``,
    ]),
    `---`,
    ``,
    `## Safeguards`,
    ``,
    ...playbook.safeguards.map((s) => `- ${s}`),
    ``,
    `---`,
    ``,
    `## Success Metrics`,
    ``,
    ...playbook.successMetrics.map((m) => `- ${m}`),
    ``,
    `---`,
    ``,
    `## Launch Style Comparison`,
    ``,
    `| Style | Fit | Score | Angle |`,
    `|-------|-----|-------|-------|`,
    ...playbook.allStyles.map(
      (s) => `| ${s.name} | ${s.fit} | ${s.fitScore}% | ${s.messagingAngle} |`
    ),
    ``,
    `---`,
    ``,
    `*Generated by LauncHappy — AI-powered launch simulation*`,
  ];

  return lines.join("\n");
}

export default function DownloadButton({ playbook, insights }: DownloadButtonProps) {
  const [open, setOpen] = useState(false);

  const download = (content: string, fileName: string, mimeType: string, format: string) => {
    window.pendo?.track("playbook_downloaded", {
      downloadFormat: format,
      featureName: insights.featureName,
      launchReadinessScore: playbook.launchReadinessScore,
      recommendedStyleName: playbook.recommendedStyle?.name ?? "",
    });

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
    setOpen(false);
  };

  const slug = insights.featureName.replace(/\s+/g, "-").toLowerCase();

  return (
    <div className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-2 px-5 py-2.5 rounded-xl glass border border-[var(--border)] hover:border-violet-500/30 text-sm font-semibold text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-all"
      >
        <Download className="w-4 h-4" />
        Download Playbook
        <ChevronDown className={cn("w-3.5 h-3.5 transition-transform", open && "rotate-180")} />
      </button>

      {open && (
        <div className="absolute bottom-full mb-2 right-0 glass rounded-xl border border-[var(--glass-border)] overflow-hidden shadow-xl w-52 z-10">
          <button
            onClick={() =>
              download(buildMarkdown(playbook, insights), `${slug}-playbook.md`, "text/markdown", "markdown")
            }
            className="w-full text-left px-4 py-3 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-white/5 transition-colors"
          >
            📄 Markdown (.md)
          </button>
          <div className="h-px bg-[var(--border)]" />
          <button
            onClick={() =>
              download(
                JSON.stringify({ insights, playbook }, null, 2),
                `${slug}-playbook.json`,
                "application/json",
                "json"
              )
            }
            className="w-full text-left px-4 py-3 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-white/5 transition-colors"
          >
            🗂️ JSON (raw data)
          </button>
          <div className="h-px bg-[var(--border)]" />
          <button
            onClick={() => {
              window.pendo?.track("playbook_downloaded", {
                downloadFormat: "pdf",
                featureName: insights.featureName,
                launchReadinessScore: playbook.launchReadinessScore,
                recommendedStyleName: playbook.recommendedStyle?.name ?? "",
              });
              window.print();
              setOpen(false);
            }}
            className="w-full text-left px-4 py-3 text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:bg-white/5 transition-colors"
          >
            🖨️ Print / Save as PDF
          </button>
        </div>
      )}
    </div>
  );
}
